name: Build obsidian plugin

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "*" # Push events to matching any tag format, i.e. 1.0, 20.15.10

permissions:
  contents: write

env:
  PLUGIN_NAME: obsidian-bookstack # Change this to the name of your plugin-id folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # You might need to adjust this value to your own version
      - name: Build plugin
        id: build
        run: |
          yarn
          yarn run build --if-present
          mkdir ${{ env.PLUGIN_NAME }}
          cp main.js manifest.json ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
      - name: Create Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${{ github.ref_name }}"
          gh release create "$tag" \
                    --title="$tag" \
                    --generate-notes \
                    main.js manifest.json styles.css \
                    './${{ env.PLUGIN_NAME }}.zip#${{ env.PLUGIN_NAME }}-${{ steps.build.outputs.tag_name }}.zip'
